version: "3"
services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    network_mode: service:clickhouse
    volumes:
      - ..:/workspace:cached
  clickhouse:
    image: "yandex/clickhouse-server:21.1.7"
    volumes:
      - ../.clickhouse:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
