version: "3"
services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - clickhouse
    volumes:
      - ..:/workspace:cached
  clickhouse:
    image: "yandex/clickhouse-server:21.1.7"
    volumes:
      - ./clickhouse:/var/lib/clickhouse
    ports:
      - "8123:8123"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
